### ISSUE TITLE
Completed mastery quizzes and clmystery challenge and unsure on how to proceed

### ISSUE THREAD

**Issue by amittauro** [makersacademy/common-knowledge#239]
Would like to review overall code for mastery quiz to see where I can improve (https://github.com/amittauro/mastery-quizzes/settings/access)
Would like guidance on next step/what to focus on before fundamentals starts.

**Comment by dearshrewdwit** [comment]
Following up from the chat we had

1. further fun to be had here: https://github.com/makersacademy/skills-workshops/tree/master/practicals/adventures/cipher-world - let me know at any point how you get on, and I'll keep pushing. Lots more exercises when you want them!
2. Let's wait to do reviews until the next module: Software Craft

**Comment by stefan22** [comment]
Hi,

Sure, but  make sure I've got access to it.  The link you've sent me is
broken.
