### ISSUE TITLE
How do I unsubscribe from this channel...?  Have tried a couple of times...!!

### ISSUE THREAD

**Issue by Finble** [makersacademy/common-knowledge#241]
**Describe the situation**
A clear and concise description of the situation.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**
Add any other context about the problem here

**Comment by dearshrewdwit** [comment]
@Finble I can't manually remove you from watching this repository without first removing you from the Makers organisation which will remove any forks that you currently have. 

On #234  I shared a couple ways to solve the problem of receiving notifications - but let me know if you'd prefer me to remove you! I can then re-invite you if you share your email address. I appreciate it's frustrating to continue to receive unwanted notifications!

> https://github.com/makersacademy/common-knowledge/issues/234#issuecomment-623071629

**Comment by Finble** [comment]
Thanks!  I've unwatched as I don't want to be removed from Makers at mo...   I had missed #234, but hopefully that's done the job - thanks @dearshrewdwit
