### ISSUE TITLE
RSPEC FREEZES 

### ISSUE THREAD

**Issue by AnastasisGi** [makersacademy/common-knowledge#244]
I  bundle exec Rspec on my mastery quizzes question 

terminal freezes as per below and I have no output of the Rspec 

...................F.FFFFF.

**Comment by dearshrewdwit** [comment]
During screenshare we narrowed down the reason for the test hanging by running the program manually and recreating the steps that the test took. During the execution of the source code a loop started and continued indefinitely. 

Essentially: there was an error in the way the loop was written.
The fix: once we found the line that was causing the failure, @AnastasisGi fixed it.
