### ISSUE TITLE
Unable to solve skills_workshops/week1/debugging_1.rb for typo in gem file

### ISSUE THREAD

**Issue by amittauro** [makersacademy/common-knowledge#245]
**Describe the situation**
Failure/Error: geocoder.search(location)[0]

**To Reproduce**
run rspec in debugging_1.rb 

**Expected behaviour**
no failures. The lookup method should return: 'Lookup.get(name)'. However running lookup returns nothing (nil).
**Screenshots**

**Additional context**
Looking to discuss this during coaching time.

**Comment by elsstrange** [comment]
@amittauro Working a bit from memory here but hope this helps:

I think you've already made your way into the really-broken-geocoder gem to take a look at the .search method, right?

And then you've gone on to look at the Query class and its .lookup method?

Why not try getting visibility in there of what `Lookup.get(name)` returns?

Then take a thorough look at the whole of the Query.lookup method, and you should spot why the method is returning nil, and be able to fix it.

(I assumed you'd rather have some tips than the answer?)


May I give you a bit of feedback on the info you've submitted with this issue?  
It would really help to have a more detailed description of the issue, for example which of the rspec tests was failing, where in the code are `geocoder.search(location)[0]` and `Lookup.get(name)`, and how/why you've identified them as the problem.  I had to rely on what I could remember from working on this with Ed on Thursday, and guess at what info you needed to get unblocked.

**Comment by amittauro** [comment]
Thanks Ellen,

So within the lookup method running puts on lookup.get: 'Lookup.get: #<Geocoder::Lookup::Nominatim:0x00007fcda5a82e68>'

I also ran puts on the variable name: 'name: nominatim'

however puts on lookup returns nil. I didn't know if its because it can't read the object in Nominatim and that's why its returning empty. See below for puts in code:

def lookup
      if !options[:street_address] and (options[:ip_address] or ip_address?)
        name = options[:ip_lookup] || Configuration.ip_lookup || Geocoder::Lookup.ip_services.first
      else
        name = options[:lookup] || Configuration.lookup || Geocoder::Lookup.street_services.first
      end
      puts "text: #{text}"
      puts "options: #{options}"
      puts "name: #{name}"
      puts "Lookup.get: #{Lookup.get(name)}"
      Lookup.get(name)
    end

    def execute
      puts "lookup should equal: #{lookup}"
      puts "text: #{text}"
      puts "options: #{options}"
      lookup.search(text, options)
    end

**Comment by stefan22** [comment]
Unsubscribe
