### ISSUE TITLE
Adding money to oyster card - tests

### ISSUE THREAD

**Issue by telads** [makersacademy/common-knowledge#248]
Amy and I were pairing on the oyster card exercises. We were trying to create multiple tests where the user adds money to their card. After several attemps, we managed to make the test work (see 1st screenshot).  After trying to replicate the issue to test my understanding, I can't understand why the terminal has got '30' when I want '25' (second and third screenshots provided).

**Correct code:** 
<img width="1440" alt="Screenshot 2020-08-19 at 23 02 55" src="https://user-images.githubusercontent.com/66533748/90695829-1e8e9a80-e273-11ea-98cd-ac4fe115fa97.png">

----------
**After replicating the issue**

<img width="1440" alt="Screenshot 2020-08-19 at 23 23 22" src="https://user-images.githubusercontent.com/66533748/90695846-251d1200-e273-11ea-9148-d047438aaf50.png">

<img width="1440" alt="Screenshot 2020-08-19 at 23 27 39" src="https://user-images.githubusercontent.com/66533748/90696128-ad031c00-e273-11ea-95dd-70b15ef3478c.png">

**Comment by telads** [comment]
Screenshots are in wrong order! The middle screenshot should be the first one.

**Comment by dearshrewdwit** [comment]
What is your reasoning behind expecting `25` for the test `A card totals money added (25)` in the replicated screenshot?

**Comment by telads** [comment]
I expected it to be 25 as I was adding 15 in addition to the 10 that was added in the previous test

**Comment by dearshrewdwit** [comment]
Remember each test should run in isolation - you shouldn't depend on previous tests.

Each test has its own set up phase , its own execute phase, and its own verify phase.

In this test
1. how are you setting up your object?
2. what code do you execute
3. and what are you verifying it should be?

**Comment by telads** [comment]
Having gone through the exercise, I understand what went wrong. 
Learning: each test runs in isolation 
The code executed was totalling 30 as it calculated the sum from lines 14 and 16
