### ISSUE TITLE
When to push back against rubocop?

### ISSUE THREAD

**Issue by elsstrange** [makersacademy/common-knowledge#249]
**Describe the situation**
I've started using rubocop alongside rspec, however I'm noticing a few surprising tests that it's applying, and I'm unsure when to push back and disable those tests.

For example, rubocop asserts that single quotes are preferable for strings, unless the string includes formatting that requires double quotes.  Conversely, a lot of formal Ruby documentation seems to use double quotes even where strings don't include formatting (e.g. [ruby-doc.org](https://ruby-doc.org/core-2.7.0/Array.html) and [rspec](https://relishapp.com/rspec/rspec-mocks/v/3-9/docs/basics/allowing-messages)). Do I listen to the cop, or disable the test?

rubocop is also advocating a type of Hash notation that I actually find less clear than rocket notation [documentation here](https://www.rubydoc.info/gems/rubocop/0.46.0/RuboCop/Cop/Style/HashSyntax) - and again, I'm not sure whether to listen to the cop or not. I want to learn good habits, but don't want to blindly trust that rubocop is always teaching me the right thing.

I'm also seeing rubocop criticising the execute/verify lines of my tests for being too long - but this seems like it's unavoidable sometimes, where a long string is the expected output/return value.  Is it usual to run rubocop on tests as well as source code?  If so, is there a way to relax its limits on spec files only? Or alternatively, is there a better way to write my tests that avoids these long lines, and keeps rubocop happy?

**Comment by dearshrewdwit** [comment]
What set of cops are you using? 

I suspect you're using the default set. It might be worth using this set: https://github.com/makersacademy/scaffolint.
